### ISSUE TITLE
Asset list does not show beyond 25 assets in the dashboard.

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#102]
Managers are currently unable to assign the new assets to the tasks in the dashboard.

**Comment by thehoneymad** [comment]
So, you need more entries in one list?

**Comment by faisalgobd** [comment]
If we are able to browse them and assign them; it will be fine. 👍

**Comment by thehoneymad** [comment]
Issue is closed and it's 50 now
