### ISSUE TITLE
ETA failed - feature not working.

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#103]
Can be found in the link: http://gofetch.cloudapp.net/api/job/Job-USKY852M

**Observed Result:**
We got,

_"ETA": "2016-09-01T06:00:00Z",
 "CompletionTime": "2016-09-05T06:19:43.754Z",
 "ETAFailed": false_

**Expected Result:**

**_"ETAFailed": true_**

**Comment by thehoneymad** [comment]
Small but solid description, thanks faisal
