### ISSUE TITLE
Reporting Controller

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#106]
# Backgroud

Currently, ops are documenting jobs in excel file and creating manual report everyday. The last reason for them not to utilize T-Rex dashboard fully is it doesn't have reporting feature. Tried to implement basic reporting through Jobs Odata but facing numerous problem. Hence, adding a very basic reporting controller on TaskCat.

The very basic format of reports ops want are given below:

![report1](https://cloud.githubusercontent.com/assets/4245521/18409056/7580cee8-7761-11e6-8432-4b0da72683c4.JPG)
![report2](https://cloud.githubusercontent.com/assets/4245521/18409057/7a0126d4-7761-11e6-8608-09b737c57bae.JPG)
![report3](https://cloud.githubusercontent.com/assets/4245521/18409059/7d9b6476-7761-11e6-834a-f6828281f1cc.JPG)

**Comment by thehoneymad** [comment]
What kind of problems through Odata? 

Anyway, we need a reporting module but building it in this way can work only temporarily. And even to implement this, the time invested can be the same if we go for something good. :)

**Comment by thehoneymad** [comment]
What is a conveyance allowance by the way?

**Comment by tareq89** [comment]
conveyance allowance is for the asset when they have to hire CNG or Rickshaw during delivery

**Comment by tareq89** [comment]
Reporting module has been requested by the ops for a very long time. Now all the b2b and b2c orders are going through the system. but since we do not have any reporting module, they are still having that excel documentation thing. Since they can generate reports through excel.
I think this is the last piece which will move ops 100% to our system.
The ops are expecting the reporting module as soon as possible.

**Comment by tareq89** [comment]
Check NerdCats/SpyCat
