### ISSUE TITLE
IMessenger interface for mailing through SendGrid or Google Mail App

### ISSUE THREAD

**Issue by thehoneymad** [NerdCats/TaskCat#16]
As per TaskCat was designed earlier, we wanted to have a IMessenger interface to notify/send message to user for anything that would require. 

Example cases would be to notify a login, order confirmation. Currently Google Mail App and Sendgrid would be just fine to integrate under the IMessenger platform.

## Guideline of working on a ticket
Assume the issue number is 123
1. Create a branch with the issue number. i.e. Issue#123
2. Work on it and create a pull request with "fixes #123" in the body.

**Comment by thehoneymad** [comment]
@mkzaman , hows it going buddy? No pressure, just asking. Need any help?

**Comment by mkzaman** [comment]
currently reading the source. Will work in weekends.

**Comment by thehoneymad** [comment]
okay @mkzaman

**Comment by thehoneymad** [comment]
@mkzaman ?

**Comment by thehoneymad** [comment]
Closing this as we have  SMTP mailer now, would integrate the ones needed later
