### ISSUE TITLE
IServiceChargeCalculationService Implementation

### ISSUE THREAD

**Issue by thehoneymad** [NerdCats/TaskCat#17]
Write a IServiceChargeCalculationService  implementation that would allow to write services that would be responsible for calculating service charge for an order.

Service Charge are the part that actually makes money in a Delivery Job, currently the job is to suggest a price for the delivery based on itemdetails . :)

**Comment by tareq89** [comment]
We need to update this mechanism!

**Comment by thehoneymad** [comment]
We can actually open a new ticket for that. Reopening a closed ticket is not a good idea. And unless there is proper guidelines/requirements for this, this is distracting.
