### ISSUE TITLE
Create Unit Tests for DeliveryOrderProcessor, DefaultOrderCalculationService, DefaultDeliveryChargeCalculationService

### ISSUE THREAD

**Issue by thehoneymad** [NerdCats/TaskCat#21]
A spawn of from #9

**Comment by Shaphil** [comment]
Minor fixes ToDo: DefaultOrderCalculationService.cs, DefaultOrderCalculationServiceTest.cs

**Comment by thehoneymad** [comment]
Is this done? Can we close this?

**Comment by Shaphil** [comment]
Features added on **commit 7387f75f113ca3f728b042851550e54e8f8fe90f**
