### ISSUE TITLE
XMLHttpRequest cannot load http://localhost:23873/token. No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#40]
POST http://localhost:23873/token 

XMLHttpRequest cannot load http://localhost:23873/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8080' is therefore not allowed access. The response had HTTP status code 500.

XHR failed loading: POST "http://localhost:23873/token".

```
General:
Request URL:http://localhost:23873/token
Request Method:OPTIONS
Status Code:400 Bad Request
Remote Address:[::1]:23873
```

```
Request Header
OPTIONS /token HTTP/1.1
Host: localhost:23873
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://127.0.0.1:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Access-Control-Request-Headers: accept, content-type
Accept: */*
DNT: 1
Referer: http://127.0.0.1:8080/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,bn;q=0.6
```

```
Response Header:
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 71
Content-Type: application/json;charset=UTF-8
Expires: -1
Server: Microsoft-IIS/10.0
X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcWmFydmlzXERvY3VtZW50c1xUYXNrQ2F0XFRhc2tDYXRcVGFza0NhdFx0b2tlbg==?=
X-Powered-By: ASP.NET
Date: Sun, 29 May 2016 06:48:04 GMT
```

**Comment by thehoneymad** [comment]
Please post code related issues under code formatting, helps to read

**Comment by thehoneymad** [comment]
## What was done

1. Added a OwinMiddleware for handling OPTIONS requests with Origin key so preflight CORS actions are filtered before authentication is done

Please check TaskCat 0.1.3.20 or above versions in TaskCatDev.

Please reopen the ticket if the problem still persists.
