### ISSUE TITLE
Searching Users by name

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#55]
The admins will be creating orders on behalf of Users.
So they need to find Users. I have tried Odata api end point but it doesn't work:
`http://taskcatdev.azurewebsites.net/api/Account/odata?$filter=startswith(UserName, 't') eq true`

So, need an api end point to search users by user name. The way I would imagine it, is, I start writing a charecter and all the username starting with that charecter will keep populating as a suggestion.

Much like google's autocomplete.

**Comment by thehoneymad** [comment]
I think the tree node parser there doesn't hand spaces well inside a odata filter method call
The following link would work.

http://taskcatdev.azurewebsites.net/api/Account/odata?$filter=startswith(UserName,'tar') eq true

If you put a space in between the method call

http://taskcatdev.azurewebsites.net/api/Account/odata?$filter=startswith(UserName, 'tar') eq true

It doesn't. LinqToQueryString can be fixed to do that of course, should be a little case of string trimming.

**Comment by tareq89** [comment]
Thanks, I blv the issue is solved now!
