### ISSUE TITLE
Should we store enterprise user's invoice along in the Jobs?

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#56]
Ops team maintains an excel sheet. I have seen what they are storing:

- SL
- Order Date
- Delivery Date
- **Their Invoice ID**
- GO Fetch Invoice ID
- Total money received
- Delivery Fees
- Delivery Status

Should we store their Invoice ID in our Jobs? I think it will make easier for ops team if they ever need to cross check our job and their actual invoice.

**Comment by thehoneymad** [comment]
Invoice ids would be obsolete as the jobs would incorporate it anyway. And invoice can be generated against any job any time. So, they do have an id and thats the same id of the job. Keeping both looks redundant for me and sums up with extra work. 

And for Invoice's from other companies that is associated with this should be stored in a different manner as we dont incorporate anything with it except the id. Im blocking it as for right now it is not that important.

**Comment by thehoneymad** [comment]
Please reopen this if needed. I dont see a point of keeping this open now.
