### ISSUE TITLE
All Delivery needs personal info for proper delivery information set

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#67]
Background:
In B2B, the order is created by vendor but ultimately delivered to the customer.
For now, we can add customer name and phone number in the NoteToDeliveryMan field, but ultimately, for a proper segregation of information, we might need fields like **end customer's name, phonenumber** etc.

**Comment by thehoneymad** [comment]
Please follow proper terms when creating an issue, this looks like a classified delivery job issue for an enterprise user. The title itself is misleading and incomplete.

**Comment by tareq89** [comment]
As far as I know, classified delivery is for vendors like eBay, where there is an extra step of collecting money from the buyer and give it to the seller.

Now, in the case of normal e-commerce companies, when they are creating orders, they are creating it as an enterprise user. But the order is delivered finally to the end customers. Hence, there is a need for end customers info. This is a requirement that might arise.

Is normal B2B deliveries fall under the classified deliveries?

**Comment by thehoneymad** [comment]
No, in that case, enterprise users should be able to use a different payload for deliveries where they need to put people's name into the system as delivery info. 

Problem is, we need to find a way to get these users start using GO! Fetch too. Invoices do have that feature but guess the order description doesn't.

I'd find a way out to augment delivery address with proper info in case of basic deliveries.

**Comment by thehoneymad** [comment]
I think this is already done, so closing this.
