### ISSUE TITLE
How the Product Type, Commission, Distance, Delivery Type will be handled in TaskCat?

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#69]
Background:
After examining the ops team's excel sheet, we found that, almost all of their fields matches with our system except these following fields:

1. **Product Type:** E-commerce, Document, Coffee, Ticket, Grocery, Vape, Food, Salad
2. **Commission:** ex: if dhaka dough's product price is 2000 and above, we get 20% of the price as a commission + our service charge!
3. **Distance:** Total distance traveled by a delivery man, right now manually calculated
4. **Delivery Type:** Same Day, Next Day [maybe this is our ETA]

How these fields should be handled in TaskCat?

**Comment by thehoneymad** [comment]
This is a nice one to be honest. Thanks for the detailed background here

1. Product Type is a good idea but sometimes orders contains multiple product type, I'd tell you to wait for #8 
2. Please wait for #66 
3. Good point, create one ticket please for this
4. Yes, that is our ETA

When you're done reading, please close this one.

**Comment by thehoneymad** [comment]
@faisalgobd have you read this?

**Comment by faisalgobd** [comment]
Yes I did. I think `3. Distance` is related to the issue #76 . Should I add an issue for it anyway?

**Comment by faisalgobd** [comment]
Ticket added. #80

**Comment by thehoneymad** [comment]
Closing this as the question has already been answered.
