### ISSUE TITLE
Cancel a Job

### ISSUE THREAD

**Issue by thehoneymad** [NerdCats/TaskCat#71]

**Comment by tareq89** [comment]
An order can be cancelled by the user, or because the user was unavailable, the order was returned and hence cancelled, right?

Do we need a field stating the reason of the cancellation?

**Comment by thehoneymad** [comment]
Right now, only administrator or a backend office user can cancel an order. Because anyone in this country can just order and cancel right after that. So, thats not a good thing to have. 

There can be multiple reasons for cancelling an order and no, not only the case where the user is not available at home. Thats not a job cancelled, thats basically a job returned. And usually in that case there has to be compensation policy.

**Comment by tareq89** [comment]
Thus, do we need a field stating the reason of the cancellation?

**Comment by thehoneymad** [comment]
I'm not going for a mandatory field, may be. First the basics are needed to be done.

**Comment by tareq89** [comment]
Great! it should not be a mandatory field, but it will be good to have one. And also, this field can be populated only if the job is cancelled.
