### ISSUE TITLE
Odata Job query doesn't return correct pagination information

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#75]
# Problem
Here's a sample Odata query:
`http://localhost:23873/api/Job/odata?$filter=State eq 'ENQUEUED'&$orderby=CreateTime desc&envelope=true&page=0&pageSize=25`

Note here that,
filter= State eq 'ENQUEUED'
envelope= true
page= 0
pageSize = 25

And the pagination property of the returned result is:

```
"pagination": {
    "Total": 25,
    "Page": 0,
    "Start": 1,
    "PageSize": 25,
    "TotalPages": 1,
    "Returned": 25
  }
``` 
It says the Total ENQUEUED jobs on the database are 25, but right now, this is not the total ENQUEUED jobs on the databse (its happened to be 35 at the time of creating this issue, on the dev db).

The related code can be found here:
https://github.com/NerdCats/TaskCat/blob/Release/TaskCat/TaskCat/Controller/JobController.cs#L184

# Expected Result

If there are 35 ENQUEUED jobs in the db, then the pagination property should look like this:

The Query :
`http://localhost:23873/api/Job/odata?$filter=State eq 'ENQUEUED'&$orderby=CreateTime desc&envelope=true&page=0&pageSize=25`

```
"pagination": {
    "Total": 35,
    "Page": 0,
    "Start": 1,
    "PageSize": 25,
    "TotalPages": 2,
    "Returned": 25,
    "NextPage": "http://localhost:23873/api/Job/odata?$filter=State eq 'ENQUEUED'&$orderby=CreateTime desc&envelope=true&page=1&pageSize=25"
  }
```

**Comment by thehoneymad** [comment]
Please have a look at 44d3bda9d3c74bdfe688ec348a49b550d55271f2 
And JobController would need unit test, so please lookout for an issue like that, if not, create one please.

**Comment by tareq89** [comment]
taskcatdev has the correct odata query pagination now.
but gofetch production doesn't have this update. Already there are orders from the real vendors on our gofetch production and due to this pagination error, our admins can not see all the orders.
Please fix a release date for releasing this fix.

For now, I am patching a temporary fix by adding pageSize param to 50 in T-Rex (since AppConstant.MaxPageSize = 50 on taskcat). But it might not be sufficient within few days.

**Comment by thehoneymad** [comment]
Merged to Prod, taking it off.
