### ISSUE TITLE
Proper guideline needed for the Service Charge.

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#76]
**Observed Problem**
Delivery Charge automatically added 150 Tk.

**Expected Result**
Proper guideline should be implemented for the Service Charge.
It should be configurable from the dashboard for different vendors.
Depending on the distance and product weight the Delivery Charge should be configurable by the Admin from the dashboard.

**Comment by thehoneymad** [comment]
It should not come from the tech team to be honest. :)

**Comment by faisalgobd** [comment]
Op team was told to bring with a list of the Delivery Charges for different vendors.

**Comment by thehoneymad** [comment]
I think someone mailed me on this. @faisalgobd can you close this?
