### ISSUE TITLE
Asset's shouldn't be able to update task state directly

### ISSUE THREAD

**Issue by fahadwajed** [NerdCats/TaskCat#77]
**Observed Problem**
Right now asset's have the ability to change the state of a task directly. This shouldn't be like this. 

**Proposed Solution**
This should be like they can only inform admin about that task. Admin will update the task state from the admin panel.

**Requirement**
The backend should provide an API which will be used to notify admin panel from asset app.

**Comment by thehoneymad** [comment]
I changed my mind about this and Id let you know why when the full implementation would be done.
