### ISSUE TITLE
jobtask initiationTime property is not populating

### ISSUE THREAD

**Issue by tareq89** [NerdCats/TaskCat#86]
# Background:
When a jobtask is updated from PENDING to IN_PROGRESS, the jobtask's initiationTime property should catch the time. Currently it is not populating.

for example, 
```
"To": {
"Address": "uttara, Dhaka",
"PostalCode": null,
"Floor": null,
"HouseNumber": null,
"AddressLine1": "uttara",
"AddressLine2": null,
"Country": null,
"City": "Dhaka",
"State": null,
"Locality": "",
"Point": {
"type": "Point",
"coordinates": null
},
"Provider": "Default"
},
"id": "6929e104-b981-46d4-9ded-d8db35f4743a",
"Type": "Delivery",
"JobTaskStateString": " is in progress",
"State": "IN_PROGRESS",
"AssetRef": "57660709b477aa9971d80425",
"ETA": "2016-10-08T07:45:00Z",
"CreateTime": "2016-08-02T09:45:24.222Z",
"InitiationTime": null,
"ModifiedTime": "2016-08-02T09:45:24.222Z",
"CompletionTime": null,
"Duration": null,
"IsReadytoMoveToNextTask": false,
"IsDependencySatisfied": true,
"IsStartingTask": false,
"IsTerminatingTask": true,
"ETAFailed": false
}
```
#What Should be Done:
When the jobTask is updated from PENDING to IN_PROGRESS, the initiationTime property should be populated and store the time when it was updated to IN_PROGRESS.

**Comment by thehoneymad** [comment]
This bug is still here! interesting

**Comment by tareq89** [comment]
http://taskcatdev.azurewebsites.net/api/job/Job-NXSG2VC8

kindly check the packagepickup job task, its completed, but the initiation time and duration is still null!
