### ISSUE TITLE
User shouldn't be able to assign new asset once the "delivery" is already "completed".

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#92]
**Observed Result:**
- User is able to assign more assets when the delivery is already **completed**.
(I was able to add 5 more!)

**Expected Result:** 
- User should **not** be able to assign more assets  when the delivery is already **completed**.

**N.B. :** ​*This test was performed on `Job-8A0QKWZO`(dev).*

**Comment by thehoneymad** [comment]
Good point!
