### ISSUE TITLE
Introducing a new payload with Recipient Info for basic B2B deliveries like we did in classified delivery workflow.

### ISSUE THREAD

**Issue by faisalgobd** [NerdCats/TaskCat#94]
It will have delivery address along with Recipient's name and phone number.

In response to issue #93

**Comment by thehoneymad** [comment]
Why can't ZuumZuum use Classified delivery as that is actually meant for B2B only?

**Comment by thehoneymad** [comment]
Understood, possible. We need a different delivery payload for them

**Comment by thehoneymad** [comment]
This has been hanging on for a while. Thus fixed it. To have a ClassifiedDelivery order with the basic delivery workflow and ClassifiedOrder order type:
1. Use Classified Delivery delivery type
2. Use Order variant "Enterprise" (previously payload type)

**Comment by tareq89** [comment]
I guess I missed this, adding this on T-Rex and WebCat order creation form.  Jira Issue GFETCH-164
